import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import client from "../graphql/client";
import styles from "../../styles/Home.module.css";
import { NavBar } from "@/components/NavBar";
import { LoadingButton } from "@mui/lab";
import { useRouter } from "next/router";
import FocusGraph from "@/components/Graph/FocusGraphWrapper";

const Home: NextPage = () => {
    useEffect(() => {
        client;
    }, []);

    const router = useRouter();
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className={styles.main}>
                <p className={styles.subtitle}>HOW PEOPLE</p>
                <h1 className={styles.title}>CYBERCONNECTED IN </h1>
                <h1 className={styles.title}>METAVERSE</h1>
                <LoadingButton
                    // loading={loading}
                    className={styles.jumpButton}
                    onClick={() => router.push("/socialgraph")}
                    sx={{
                        ":hover": {
                            bgcolor: "#555",
                        },
                    }}
                >
                    Let&apos;s jump in!
                </LoadingButton>
            </main>
            <FocusGraph />
        </div>
    );
};

export default Home;
