import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import client from "../graphql/client";
import styles from "../../styles/Home.module.css";
import { WalletConnectButton } from "@/components/WalletConnectButton";
import { NavBar } from "@/components/NavBar";
import { LoadingButton } from "@mui/lab";
import { useRouter } from "next/router";

const Home: NextPage = () => {
    useEffect(() => {
        client;
    }, []);

    const router = useRouter();
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className={styles.main}>
                <p className={styles.subtitle}>HOW PEOPLE</p>
                <h1 className={styles.title}>CYBERCONNECTED IN </h1>
                <h1 className={styles.title}>METAVERSE</h1>
                <LoadingButton
                    sx={{ bgcolor: "white", width: "300px" }}
                    onClick={() => router.push("/socialgraph")}
                >
                    Let's jump in!
                </LoadingButton>
            </main>
        </div>
    );
};

export default Home;
