import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import client from "../graphql/client";
import styles from "../../styles/Home.module.css";
import { WalletConnectButton } from "@/components/WalletConnectButton";

const Home: NextPage = () => {
    useEffect(() => {
        client;
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p className={styles.subtitle}>HOW PEOPLE</p>
                <h1 className={styles.title}>CYBERCONNECTED IN </h1>
                <h1 className={styles.title}>METAVERSE</h1>
                <WalletConnectButton />
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
